#!/bin/sh
[ -z "$1" ] && echo "Error: should be run by zcip" && exit 1

. /lib/functions.sh
. /lib/netifd/netifd-proto.sh

setup_interface () {
	proto_init_update "*" 1
	proto_add_ipv4_address "$ip" '255.255.0.0'
	proto_send_update "$INTERFACE"
}

deconfig_interface() {
	proto_init_update "*" 0
	proto_send_update "$INTERFACE"
}

case "$1" in
	deconfig)
		deconfig_interface
	;;
	config)
		setup_interface
	;;
	*|init)
	;;
esac

exit 0
